### ISSUE TITLE
Assessment tool causes DB crash

### ISSUE THREAD

**Issue by khaledsabek** [chamilo/chamilo-lms#4457] opened 2022-11-16 13:59 UTC
Of course, Thank you for your hard work and dedication to Chamilo and for keeping it maintained and free, Thank you.

**Describe**
I have approximately 40 students in a class, and have 8 subject grades uploaded to the assessment tool of this class. Whenever I try to access the assessment page, it is extremely slow to open, and then when the students are trying to open, few get through and then the whole portal crashes and gives a page with the message that the db has crashed please contact the administrator. Something along these lines.

**To Reproduce**
Create a class with 40 students, 
add 8 subjects within a folder in the assessment tool
Try accessing the assessment page you will find its slow
Try accessing the assessment page as a student concurrently for the students, the portal will crash.

**Expected behavior**
It shouldnt?

Screenshots:
![Screenshot_20221116-145556_Chrome.jpg](https://user-images.githubusercontent.com/73699343/202199597-ec4d60f4-f6a2-4543-bf9b-74cf3eb01c67.jpg)

**Desktop (please complete the following information):**
 - OS: Namecheap stellar shared hosting not sure of further details [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser all browser types and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo: latest version of Chamilo 1.11.16 [e.g. 1.11.8, 1.11.x of 2018-12-01, ...]

 - Version of PHP: [e.g. 5.6, 7.2, ...]

**Additional context**
I do have other students on the portal but they arent all trying to access it at the same time, and certainly not the class of only 40 students.

**Comment by NicoDucou** [comment] 2022-12-07 14:24
HI @khaledsabek 

It should not be really slow and it should not make the BD crashes.
I just reproduced the case on the Chamilo test plateform here https://11.chamilo.org/main/gradebook/index.php?cidReq=GH445740STUDENTSWITH8ELEMENTINGR&id_session=0&gidReq=0&gradebook=1&origin=&& (enter with admin as user and password).

If the DB crashes with a simple test case I would check the hosting configuration.

Other than that, the gradebook (assessment tool) can be really resource consuming because of the average calculation. There are many options to try to make it work the best way it could to correspond to ones need.

Here are a few options that could be use full for you 

```
// Enable best score column in gradebook. Previously called disable_gradebook_stats
//$_configuration['gradebook_enable_best_score'] = false;
// Hide gradebook graph.
// $_configuration['gradebook_hide_graph'] = false;
// Improve speed when rendering gradebook student reports using Doctrine APCU cache
// $_configuration['gradebook_use_apcu_cache'] = true;
// Allow gradebook stats
// Requires to edit the GradebookLink.php And GradebookEvaluation.php files adding the "@" in the ORM phpdoc block
/* ALTER TABLE gradebook_link ADD score_weight DOUBLE PRECISION DEFAULT NULL, ADD average_score DOUBLE PRECISION DEFAULT NULL, ADD best_score DOUBLE PRECISION DEFAULT NULL, ADD user_score_list LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)' ;
ALTER TABLE gradebook_evaluation ADD score_weight DOUBLE PRECISION DEFAULT NULL, ADD average_score DOUBLE PRECISION DEFAULT NULL, ADD best_score DOUBLE PRECISION DEFAULT NULL, ADD user_score_list LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)' ;
*/

//$_configuration['allow_gradebook_stats'] = false;

```

I let you check with your hosting and try those option to be configured in app/config/configuration.php

Best regards

**Comment by ywarnier** [comment] 2022-12-30 16:25
Closing (no feedback)

**Closed by ywarnier** 2022-12-30 16:25 UTC
Labels: Question / Support, On hold - Can't reproduce
