### ISSUE TITLE
Portal News appears to every learner no matter what Group i choose 

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3541] opened 2020-09-27 19:04 UTC
Dears,

First of all i contacted Beeznest to inquire about adding some features to the site and they replied and recommended to wait till the release of the new version of Chamilo then they will work on the features which make sense but unfortunately some errors/bugs can't wait because it is critical for us as a school and we use it daily and being not functioning as it should be caused us a lot of troubles today. So it would be great to be able to receive help here because i am not asking for new features i am just asking to get the current features to work properly. 

Today we needed to post a "portal news" for certain classes "they all represent learners" in our school and we needed to do this for 14 different class so we created 14 different portal news "It would be great if we can select multiple groups at once" but instead of this news appears to the selected group only, it appeared to all learners instead so all learner in our site received 14 notifications and 14 emails from our school.

**To reproduce:**

- Create new portal news.
- Select visible to learners
- Choose "Announcement for a group" and select any group
- Click add news
- Now login to the website using any learner account and you will find the news visible for him even if he is not in the group you selected. 

Problem reproduced on 11.chamilo: https://11.chamilo.org/main/admin/system_announcements.php?action=edit&id=18

It would be great if there is a quick fix for that. Thank you in advance.

**Comment by tanchon** [comment] 2020-12-08 06:17
Hi,
I had the same experience as @aelalfey . 
I add that, when we choose the "send mail' option and select one group, the issue also occurs  : the mail is sent to every groups.
Tanchon

**Comment by NicoDucou** [comment] 2021-04-21 19:59
The problem is fixed with those commits included in branch 1.11.x

**Closed by NicoDucou** 2021-04-21 19:59 UTC
Labels: Bug
