### ISSUE TITLE
Private course continues to be visible (but not accessible) to everyone

### ISSUE THREAD

**Issue by KiLiMaToS** [chamilo/chamilo-lms#4212] opened 2022-03-21 19:50 UTC
Actually I don't know if this is a problem or if it was intentionally thought so.
If a course is set as private (therefore accessible only to a defined group or user list) it continues to be viewed by everyone. It is not actually accessible, but I don't think it should be viewed as private.
I believe this should not be happening and that it is a malfunction.

**Comment by ywarnier** [comment] 2022-03-21 21:48
Where do you see it? In the course catalogue?
There is an option for that in the first section of platform settings:
![hide-private](https://user-images.githubusercontent.com/609839/159369191-89a96869-be06-4792-8899-01b9145b037f.png)

**Comment by KiLiMaToS** [comment] 2022-03-21 22:32
yes, I have seen option, but the courses are not hidden… so I thought it was a problem.  Setting is already on YES to hide them, but this doesn't seem to work.  (forgive screenshot in Italian language)
![E6F9C352-BF01-439A-A0BF-0F64C52E147F](https://user-images.githubusercontent.com/64029935/159373879-ff748f26-366a-413e-a808-e88e7e99dbf9.jpeg)

**Comment by ywarnier** [comment] 2022-03-22 01:32
Confirmed! This must be a recent little mis-hap. We will fix this soon and update here when we got a fix.

**Comment by ywarnier** [comment] 2022-03-22 01:33
Actually no :sweat_smile: 
I had forgotten to set my course as private, but when set private, it disappears from the catalogue... Can you be more specific about the steps you follow and your version of Chamilo ?

**Comment by KiLiMaToS** [comment] 2022-03-22 10:35
I'm trying, it doesn't let me upload screenshots, I try to describe: 
1 - with admin user I set the course to private.  

2 - I have set up two "real" users in the user list for the course.  

3 - I logged in with a demo user who is not on the course list.  

4 - as soon as I log in, I see the course in the user's list.  

5 - if I try to enter the course it does not let me in and tells me that the subscription is not available.

with the screenshots everything would be clearer, I will try later to attach the screenshots I have prepared

**Comment by KiLiMaToS** [comment] 2022-03-22 11:03
Here are some screenshots ... unfortunately it doesn't let me upload photos here on GitHub:
https://photos.app.goo.gl/tpfDsprkxwLSzL5j7

**Comment by KiLiMaToS** [comment] 2022-03-23 22:00
Were you able to view the screenshots?  Why did he remove the bug tag without displaying the problem?  I have reported exactly the steps.  Currently there is only one course in the catalog, did you also reproduce the same situation to rule out that it is a bug?

**Comment by ywarnier** [comment] 2022-03-24 21:08
@KiLiMaToS not yet. The bug tag is for us contributors internally. When we tag it as a bug, it means we could reproduce it. If we can't, we don't tag it yet. This is to organize ourselves "internally", but it doesn't mean this is not a bug. Just that it wasn't confirmed by us yet. This is free software, we can't work on all these reports full time, but we will look at them at some point and ask you for feedback if we need. If you need commercial (faster) support, please contact the official providers https://chamilo.org/providers

**Comment by ywarnier** [comment] 2022-03-25 13:07
@KiLiMaToS I saw the screenshots. This has nothing to do with the catalogue, though, so the option you are using does not affect the page you are looking at. One misunderstanding solved.
Now looking at the real issue...

**Comment by ywarnier** [comment] 2022-03-25 13:15
OK, I think it's a misunderstaning issue and maybe a bug at the same time.
Are you using Chamilo 1.11.16 ?
In your screenshots, you show that the course you mention has been marked as "Special course" in the course settings (configured as admin, almost the last setting on the page).

![special-course](https://user-images.githubusercontent.com/609839/160127276-e543899d-bb08-43b9-a3f4-00b81295bd44.png)

This has the effect of always showing the course on top of the list of courses, for all users, even the ones not subscribed to it.

Normally, setting a course as "Special" supposes that the course is open. Otherwise the access gets a bit weird. You set the course as private *and* as special at the same time.
On my 1.11.16, this works: I can then connect with a demo user, see the course, click it and I get automatically subscribed. But I do remember that this used to fail in some previous version of Chamilo.
So my guess is you can fix it by either removing the "Special course" check or by updating your Chamilo installation to 1.11.16.

**Comment by KiLiMaToS** [comment] 2022-03-25 13:40
I've actually added special course in the various attempts I've made to fix the problem.
The problem was there even before I put special course flags.
![image](https://user-images.githubusercontent.com/64029935/160130528-9c1dadcd-b7f3-4307-86ad-e7d524a73d78.png)

My version is 1.11.16
![image](https://user-images.githubusercontent.com/64029935/160130429-e88186a5-42ed-4451-a6af-6be1463e0795.png)

Anyway i think i solved it, i cleaned whole site and reinstalled everything, now it seems to work.

**Now I just have to solve the problem of marking a session as "completed", only after seeing a video completely. As soon as you click on the session but when the video session ends.**
Then it is really perfect!

Thanks for help

**Comment by ywarnier** [comment] 2022-03-25 14:33
Completeness of courses/sessions is only available through the Gradebook tool, which can be linked to a learning path.
But you won't find an option in Chamilo to mark a step as complete only when you finish a video. That's not a feature yet.

**Closed by ywarnier** 2022-03-25 14:33 UTC
Labels: Question / Support

**Comment by KiLiMaToS** [comment] 2022-03-25 15:05
I meant the ability to move on to the next chapter only after completing (full video) the previous chapter.
Maybe a feature for the foreseeable future ... thank you very much!

Greetings
