### ISSUE TITLE
Error de la videoconferencia BigBlueButton con PHP 5.6 y Chamilo 1.11.8

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2706] opened 2018-10-22 15:10 UTC
### Current behavior / Resultado actual / Résultat actuel
La sala de videoconferencia no se abre, mostrando una pantalla en blanco que no deja de cargar.

### Expected behavior / Resultado esperado / Résultat attendu
Debería abrir la sala y mostrar la interfaz de BBB

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Disponer de Chamilo 1.11.8 instalado en un entorno con PHP 5.6 y con la videoconferencia Big Blue Button 
Activar el plugin de videoconferencia, acceder a un curso como profesor e intentar entrar en la sala de videoconferencia
### Chamilo Version / Versión de Chamilo / Version de Chamilo

Probado en Chamilo 1.11.8 y Big Blue Button 2.0 RC

NOTA: en un entorno con PHP 7.2 y las mismas versiones de Chamilo y BBB funciona correctamente.

**Comment by ywarnier** [comment] 2018-10-22 15:13
So the report is that the BBB plugin does not work with BigBlueButton 2.0 RC and PHP 5.6.
Due to the fact that PHP 5.6 is about to go out of maintenance (see http://php.net/supported-versions.php) and that BBB 2.0 is pretty recent, we won't be fixing this. Please make sure you use PHP 7.0 or higher for Chamilo to avoid the issue.

**Comment by ywarnier** [comment] 2018-10-22 15:14
Thanks for reporting :+1:

**Comment by caos30** [comment] 2020-06-29 21:55
Hello, i've exactly the same problem. I'm using php7.2+ on both servers (Chamilo & BBB). Both run perfect alone, but i am not able to open a conference room from Chamilo.

I installed the plugin Videconference (v 2.7) on Chamilo (v1.11.10) on a shared hosting. I installed BBB on a DigitalOcean droplet in his last version (2.2).

I configured the plugin on Chamilo with the URL https://bbb.mydomain.com and the secret key got from SSH command ```bbb-conf --salt```. In the settings of the Chamilo plugin i enabled the global conference room, so now, from Main Page i have the possibility to "open/create" a new conference room: i get a form with the UTL of the conference to be shared. But when i click on the button to access room i'm redirected to this URL:

https://chamilo.mydomain.com/plugin/bbb/start.php?launch=1&global=1&user_id=10

But it remains fully empty :-|

The most curious is that if i visit again the Global Conference link on Main page, it show me that i ave an OPEN room. In fact, if i repeat several times these steps, the list of open rooms increase ecah time. 

I suspect that the plugin is failing or not connecting with BBB server really.

Regarding this question i've unsuccessfully tested two possible URL of BBB server:

https://bbb.mydomain.com/bigbluebutton/
https://bbb.mydomain.com/

The first one is the got when you use the SSH command ```bbb-conf --salt``` on the BBB server, and it's suposed to be the one to use. But as it didn't, i tried with the second one. But, noen of them works.

Maybe i'm doing something bad. It really the documentation on Chamilo is not so detailed explaining this issues. I must to guess some things.
So, any help is welcome. I also wrote this comment to serve as help to future users ;-) I will add a  last comment when i got it run!

**Comment by caos30** [comment] 2020-06-30 04:54
### -- [SOLVED] --
The cause of the problem is the chamilo plugin. The solution is **very easy**: edit the file 

```/plugin/bbb/lib/bbb_api.php```

and add this line #74: 

```$url = str_replace('https://https://','https://','https://'.$url);```

In other words: i discovered that the URL received by the method 

```private function _processXmlResponse($url){``` 

sometimes don't have the **https://** at the beginning. So the solution is to add it and with the _str_replace_ we avoid to add it twice. Magic: instantly worked as expected the integration of Chamilo with BigBlueButton!!! (hehehe, _"instantly" means after 4 hours of hard debugging work to find the problem!_).

I think that this line should be added to the official code of the plugin.

### Note: about URL of BBB server

By the way, the URL to put on the plugin settings must not to end with the word "**bigbluebutton**", because the plugin add it automatically. So instead of 
```
https://bbb.mydomain.com/bigbluebutton/
```
you must use:
```
https://bbb.mydomain.com
```
I think that it would be useful to note this on the settings page, around that setting ;-)

**Comment by ywarnier** [comment] 2020-07-01 00:40
@caos30 could you share the output of the `bbb-conf --secret` URL line (not the secret line) with us to compare to what we have on the BBB server side? Do not include the whole string, just the beginning to see whether this one includes the protocol or not (before use by Chamilo).

**Comment by ywarnier** [comment] 2020-07-01 01:00
In our case we have something like:
```
    URL: https://bbb.domain.com/bigbluebutton/
```

**Comment by caos30** [comment] 2020-07-01 01:56
Hello @ywarnier , the output of ```bbb-conf - -secret``` in my BBB server is something like yours: 

- begin with: ```https://bbb.```
- ends with: ```.com/bigbluebutton/```

As i said in my previous message, i think that it's not harmful to add the code line i suggested to be sure that it began with ```https://```:

```
$url = str_replace('https://https://','https://','https://'.$url);
```
I suppose that _in another place of the Chamilo plugin_ __the "https" disappear__, because i really included this part of the url in the settings of the module, you know, above the secret key to encryption.

**Comment by caos30** [comment] 2020-07-01 02:55
@ywarnier  i modified the comment where i shared my __patch__ specifying where to put my "patch" with other words: instead of specify number line, i put above which line of code must be put. 

If i would put this correctly on yesterday, today the other user that had the same problem who you tried to help too, would fix his problem on his first attempt.

Anyway, if you will add this "patch line" to the code of the module, i know you will put it in the best place ;-)

Cheers! And thanks again for this great plugin!!

**Comment by ywarnier** [comment] 2020-08-10 22:25
I believe this patch about the url and protocol solves the issue too: 1cf8744

**Closed** 2022-05-17 20:38 UTC
Labels: Bug, Requires testing/validation
