### ISSUE TITLE
Progress from 0% to 100% in a single click (using Ispring Authoring Tool)

### ISSUE THREAD

**Issue by JeanLAlves** [chamilo/chamilo-lms#2966] opened 2019-08-07 21:48 UTC
Hi, people! 
I'd like to report the following issue related to the Progress bar when uploading the index of contents created in Ispring Suite. 

**Steps:** 
Create a learning path > edit learning path > send files to server > send content in .zip files > choose the index file of each .zip file > drag and drop the index files under the learning path name

**Problem:** 
When the couse is accessed it opens chamilo's window and shows the first content from the index file, however the progress bar advances and the topic is marked as finished right after clicking on it and without achieving the last slide or accomplishing the tasks. In oder words, the progress bar goes from 0% to 50% (there are 2 files, being 50% each) in the same time of the click. It happens the same to all other index files. (see attachment for a better understanding)

Have you already had any similar situation?

Thank you all in advance.

![WFVq4AOM6C](https://user-images.githubusercontent.com/53061593/62660164-b7da5f80-b943-11e9-810a-a376285e0d3c.gif)

**Comment by ywarnier** [comment] 2019-08-08 13:48
Hi @JeanLAlves 
It looks like your content is not considered SCORM 1.2 content somehow (possibly because it does not send the right calls at the right moment). This might be due to the content not being SCORM 1.2 but SCORM 2004 (Chamilo only supports SCORM 1.2) or some other issue with sending the SCORM LMSInitialize(). In both of these cases, Chamilo might use a fallback behaviour which just considers the content as basic HTML (or "asset" in SCORM terminology) and marks it as complete as soon as it is opened.

To increase your chances of success:
- make sure iSpring exports in SCORM 1.2 format
- make sure each item is considered as "SCO", not "Asset" (we don't know iSpring but there should be an option for that)

If things come to that, as an administrator you can enable debugging in SCORM content by:
- clicking on the ladybug in the learning paths list in Chamilo
- opening your browser's console while on the learning path viewing page
- checking for an LMSInitialize() call

**Comment by Coursenligne** [comment] 2019-08-09 06:22
In addition, iSpring is anexternal authoring tool.
The progress bar is moving forward or when the trainee enters the content or after the content is completed. Here it loks like "complete" is sent to the platform when entering the content.
As an example, if you use Storyline, export in SCORM 2.1 (otherwise the package even doaesn't load at all), the progress bar goes from 0 to 100% without any transition regardless the number of screens you have.
I haven't seen the option to make each item as SCO. As far as I know, SL works with Assets. I'll investigate more, but it looks like Chamilo reacts as it should do here.

**Comment by marshel** [comment] 2019-08-23 11:59
Maybe is a server related issue?
I had this kind of errors occasionally. Maybe the server is overloaded and can't initialize the content or it threats as HTML fallback until its full loaded. Or is a server cache issue... I could not pinpoint the cause when it happened.

**Comment by ywarnier** [comment] 2020-06-18 06:56
Long time with no particularly useful feedback. Closing.

**Closed by ywarnier** 2020-06-18 06:56 UTC
Labels: Question / Support
