### ISSUE TITLE
0Kb file downloaded when creating student report

### ISSUE THREAD

**Issue by virtualorbis** [chamilo/chamilo-lms#3003] opened 2019-10-01 15:49 UTC
I have problems exporting CSV student reports in a running Chamilo LMS
(I receive a blank 0Kb file) but the PDF option works fine, so 
I believe there is a permission error in the configuration of my installation
![informe-alumnos-csv](https://user-images.githubusercontent.com/55451742/65978348-2bc35080-e439-11e9-87bd-dda6f79aadea.PNG)

**Comment by chinovelasco** [comment] 2019-10-03 17:31
After further checking we discovered that CSV are correctly being created in this folder
/chamilo/app/cache so I don't understand why downloaded files measure 0kb

BTW I also noticed a warning message related to an apcu module

![error-apcu](https://user-images.githubusercontent.com/55451742/66149931-c22e7800-e5d9-11e9-9597-a9be9aca0e59.PNG)

**Comment by chinovelasco** [comment] 2019-10-03 19:21
We managed to install the apcu module that was missing but the problem remains.
Any suggestion before we start to modify the Chamilo php code itself?

**Comment by ywarnier** [comment] 2019-10-03 21:22
If the CSV is correctly created in app/cache/, the process of generating the CSV is OK, but not the process to send it. Are you using apache?
I would guess this is a PHP or web server configuration (or even firewall) issue that does some kind of weird cropping of the file. Are you able to download something else? (like, say, a document in the documents tool by clicking the floppy icon?)

**Comment by chinovelasco** [comment] 2019-10-03 21:43
The runcloud setup I am using installs Apache behind NGNIX.
BTW reports generated in PDF are working fine.
We changed to some php files and some CSV reports started to download

**Comment by ywarnier** [comment] 2019-10-04 06:14
Some PDF and CSV files are generated and sent on the fly, while others are stored in app/cache/ and then given as a download link (usually, if there is a download link, that means it is stored in app/cache/, but the opposite is not always true).
Can you give an example of one change you did to make CSV download work? (just to see if we can find something that works in all cases without compromise)

**Comment by chinovelasco** [comment] 2019-10-09 17:47
Sorry for the delay.
You can find my changed php file in the attached zip archive.

[document.lib.zip](https://github.com/chamilo/chamilo-lms/files/3708737/document.lib.zip)

**Comment by ywarnier** [comment] 2020-07-02 22:05
Despite many attempts (over time) at reproducing this issue, we still haven't been able to generate a 0KB file or have it download as 0KB. I suggest you seek help from an expert PHP developer to look at your issue personally.
In your configuration (Nginx in front of Apache), some settings could block the flow for some types of files.
You mentioned the CSV file was indeed created in app/cache/. If so, you should be able to access it directly through your browser giving the full path. If this is the case, then the issue might be in PHP. If not (if you cannot download it that way either), then the issue is not in PHP but in your web server configuration, somehow.
I'm closing this issue because it seems (to me) to be one of those specific cases we will never manage to reproduce on our side.
Feel free to continue commenting on the issue if you find more information, but I do not consider this a Chamilo issue until proven otherwise. Sorry.

**Closed by ywarnier** 2020-07-02 22:05 UTC
Labels: Bug

**Comment by ywarnier** [comment] 2020-07-02 22:08
A few more details:
* we usually recommend against having 539 users in one single course (sessions might prove a more efficient way to manage these). This can have an impact on the memory usage for the generation of the CSV, as this particular report gets data from *many* database tables
* we use ourselves Nginx as reverse proxy in production environments, so this is not "just because" Nginx is in front of Apache.
