### ISSUE TITLE
Grading Model Bug (No.1)

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3406] opened 2020-07-26 12:14 UTC
Dears @NicoDucou @ywarnier @AngelFQC , 

As per @NicoDucou advice. I will create separate topic for each bug to make it easier for you awesome guys to track.

**Description:** Can't create more than 11 components inside grading model. For example "in our case we need to create around 22 components inside our Grading Model."

I have recreated the case at https://11.chamilo.org/main/admin/grade_models.php?action=edit&id=1

![87872468-1e238b00-c9b9-11ea-9337-7285c9cf5109](https://user-images.githubusercontent.com/33488577/88478616-2c8a1d80-cf4a-11ea-8b8d-607f9c8ae5c3.jpg)

Thank you once more for your help.
Regards

**Comment by NicoDucou** [comment] 2020-07-27 09:53
@jmontoyaa 

When on the page https://11.chamilo.org/main/admin/grade_models.php?action=add if you click on the "+" buton at the botom right it adds a new line with the javascript:plusitem(X).
It works fine until we get to the line with the boton javascript:plusitem(11) which generates the following error in the javascript console : 
```
Uncaught TypeError: document.getElementById(...) is null
    plusItem https://11.chamilo.org/main/admin/grade_models.php?action=add:91
    <anonymous> javascript:plusItem(11):1
grade_models.php:91:12
    plusItem https://11.chamilo.org/main/admin/grade_models.php?action=add:91
    <anonyme> javascript:plusItem(11):1

```

**Comment by jmontoyaa** [comment] 2020-07-29 06:54
The value is hardcoded to a max of 10 elements, I just changed it to 20.

**Comment by NicoDucou** [comment] 2020-07-31 13:08
OK, now we can add 20 elements before getting the problem.
It could be a new enhancement to be able to configure this settings. But this is not a bug so it could be asked in a new issue if it is necessary.

I close this task.

**Closed by NicoDucou** 2020-07-31 13:08 UTC
Labels: Bug, Requires testing/validation

**Comment by aelalfey** [comment] 2020-08-09 08:30
Hi @NicoDucou @jmontoyaa 

Thank you for your reply. Can you please point me to the file to change the value to be more than 20? In our case, we want it to be 26.

Thank you in advance.

**Comment by ywarnier** [comment] 2020-08-09 21:36
You can find it in jmontoyaa's commit: https://github.com/chamilo/chamilo-lms/commit/a50c07ad22953fd83aae6a95a3e7ece24ea59b48
