### ISSUE TITLE
Audio files not saving

### ISSUE THREAD

**Issue by ConsultPW** [chamilo/chamilo-lms#2113] opened 2017-08-15 14:50 UTC
### Current behavior / Resultado actual / Résultat actuel
Adding audio to a learning path - The files do not appear to save.  The only way we can get audio onto a page is to insert it via the editor.

### Expected behavior / Resultado esperado / Résultat attendu
After clicking on the 'add audio' button it should be possibe to browse for files and add them to each page.  The files hould save in the audio folder. 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a balnk course
Add a few pages
From teacher view, click add audio
Select audio files for each page
Click on 'Save audio' .  The files are not saved!

### Chamilo Version / Versión de Chamilo / Version de Chamilo
On own system - 1.11.4
Also tried at https://campus.chamilo.org with same result.

**Comment by ywarnier** [comment] 2017-12-04 23:59
OK, I cannot exactly confirm what you are reporting: for me, uploading the MP3 files work, and I've tried with several files of more than 10MB each. I tried doing a first upload, then deleting, replacing, etc... everything works.
However, there is another issue now in 1.11.x, which is that the audio file doesn't get updated when, as a student, you switch from one learnpath item to another (it just stays on whichever the first was), which is kind of as critical as the bug you reported.
So to be clear, I attach 1.mp3 to doc 1, 2.mp3 to doc 2, 3.mp3 to doc 3, and when I load the learning path for the first time, it shows doc 1 with 1.mp3 (and that's what is expected). But when I click on doc 2, the doc 2 appears, but the audio player area remains unchanged, and the 1.mp3 is still playing.

**Comment by ywarnier** [comment] 2017-12-05 00:01
@jmontoyaa could you have a look at why audio files do not change when we "switch_item"? It used to change in previous versions, before @aragonc changed the design to remove a lot of bad, non-responsive HTML we had in there. So maybe some tag was removed that is supposed to be updated.

**Comment by jmontoyaa** [comment] 2017-12-05 12:21
@ywarnier I just fixed the issue when changing the step, but I couldn't reproduce the main error of this issue.

**Comment by ywarnier** [comment] 2017-12-05 14:12
@jmontoyaa me neither, I think the main issue is not an issue anymore. Let's wait for a few days to get feedback (on 11.chamilo.org) from @ConsultPW. If we don't, I think it's safe to close it now, because we cannot reproduce the initial issue (although there's still something wrong with Nginx's config and the files there are not loaded correctly, but that's another story).

**Closed** 2017-12-11 11:49 UTC
Labels: Bug
