### ISSUE TITLE
Integrate VR support in mediaelement (for testing)

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2622] opened 2018-08-09 00:51 UTC
https://github.com/mediaelement/mediaelement-plugins/issues/4

**Comment by ywarnier** [comment] 2018-08-10 01:41
@jmontoyaa could you have a look at this to see if you are luckier than us? We are having trouble with integrating the mediaelement plugin to allow for VR videos.
Whenever we activate it, the videos stop playing (the play button launches the audio but the video becomes hidden in CSS). @AngelFQC sent a PR with that if you can have a look at it.

Also, I'd like to have it enabled as a right-click option (to be more discreet because you cannot detect if it's a VR/360 video or not) but that doesn't seem to be possible. If you see something that can be done... (this part is optional and I'm not even sure I really want to hide it yet)

**Comment by ywarnier** [comment] 2018-08-10 01:42
If it doesn't work, then we'll just forget about it, but I would be sad.
The plugin (see link above) has a folder called "examples" with a few videos so you can download them and play them locally.

**Comment by jmontoyaa** [comment] 2018-08-10 10:34
This is a bit more complex than just adding the plugin.

I managed to make it work, but then all the videos are treated as a VR video.

Probably we will need a special button in ckeditor to include a special div class "vr_video", so the VR videos will be only managed by this:

```
$('.vr_video').mediaelementplayer({
            pluginPath: _p.web + 'web/assets/mediaelement/build/',
            features: ['{{ video_features }}'],
            success: function(mediaElement, originalNode, instance) {
            },
            vrPath: _p.web + 'web/assets/vrview/build/vrview.js'
        });


```

And the rest of videos will be managed by the classic mediaelementplayer()  definition.

In my change now it works with the example video congo_2048.mp4


https://github.com/Yonet/WebVRSlides

**Comment by jmontoyaa** [comment] 2018-08-10 10:37
My change https://github.com/chamilo/chamilo-lms/tree/AngelFQC-2622

**Comment by AngelFQC** [comment] 2018-08-10 22:17
I sent the PR #2624 to integrate the ckeditor video and allow indicate if the 360 player is enabled

**Comment by ywarnier** [comment] 2018-08-11 03:12
I reverted the pull request. This is pending a fix somewhere. The generated video tags are appended with the HTML attribute about 360 videos, but somehow the player is not updated. It feels like something is missing from the PR.

**Comment by ywarnier** [comment] 2018-08-11 04:41
OK, so in the end we enable the VR plugin by default but it's only used if the video has been uploaded through ckeditor and marked as VR there. Only the video tag is modified, so there is no other knowledge by Chamilo that the video is VR (if someone uses the same video somewhere else without marking 360°, then it will be considered a normal video).

There were issues on my server, apparently related to the fact that web/assets/ had not been regenerated properly or that some browser or server cache somewhere still provided me with a previous version of mediaelements. After deleting web/* and vendor/* and starting composer update again (and cleaning the cache), the problem disappeared.

So I am closing this last issue. The release will be postponed to this week-end to avoid any tiredness mistake.

**Comment by jmontoyaa** [comment] 2018-08-13 06:29
I tried also that and it's not working. I tried in 11.chamilo.org and it doesnt work:

https://11.chamilo.org/main/document/showinframes.php?cidReq=GAMIFICATION&id_session=0&gidReq=0&gradebook=0&origin=&id=16573

**Comment by jmontoyaa** [comment] 2018-08-13 06:32
I saw that "plugins/vrview/vrview.css" is added twice as well as the vrview.js ...

**Comment by jmontoyaa** [comment] 2018-08-13 06:45
Fixed double include with:
https://github.com/chamilo/chamilo-lms/commit/8204c6f64eff124242903ccaeb4e990b3fe33b66

**Comment by jmontoyaa** [comment] 2018-08-13 06:52
I found out that @AngelFQC modified the original third party "vrview mediaelement plugin".
I don't agree with this change because this will be hard to maintain and we don't modified third parties libraries.

Also the tag "data-360video" is not recognize and I cannot reproduce the video. 
Did you tried to make it work in 11.chamillo.org?

**Comment by ywarnier** [comment] 2018-08-13 07:03
It works with normal videos: https://11.chamilo.org/main/course_home/course_home.php?cidReq=VR
You might need to clean your cache really well. I had issues too with the video loader originally but after a full cleanup of web/ + composer install, it worked.
I authorized the modification of the plugin itself because it was clearly broken and because this is the last iteration in the 1.11.x branch. Clearly, not ideal, but acceptable given it is not in vendor and we will not update that one in the future. It can be re-instated as the original version in the master branch.

**Comment by ywarnier** [comment] 2018-08-13 07:04
In documents it doesn't work because it would require to include the .js + .css inside all documents. To avoid that, I have added a note in the 360° tab to explain that it only works with dynamic pages.

**Comment by jmontoyaa** [comment] 2018-08-13 07:09
That information should be at least added here. ok, closing. Works for me in the course tool introduction.

**Closed by jmontoyaa** 2018-08-13 07:09 UTC
Labels: Feature request
