### ISSUE TITLE
bug in Learning paths

### ISSUE THREAD

**Issue by josueco123** [chamilo/chamilo-lms#4442] opened 2022-10-31 16:33 UTC
![image](https://user-images.githubusercontent.com/45926578/199059975-04d86e9c-0bdb-4c54-a879-d1c4e3923d73.png)

we can't create a learning path because we have this bug in the view, we are working with chamilo 1.11.16

*

**Comment by NicoDucou** [comment] 2022-12-07 14:02
This is a duplicate of issue #4397
Since the other issue was in french I will translate here the answer : 
Hello @josueco123 
The problem does not reproduce on the 11.chamilo.org test platform, I think it is related to an issue with the stylesheet not applying well.
We can see on https://11.chamilo.org/main/lp/lp_controller.php?action=add_item&type=step&lp_id=360&cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin= that everything is displayed correctly:
![image](https://user-images.githubusercontent.com/6579268/206199004-7f716c15-8811-4307-a3c3-fe70b60ad479.png)

I'll let you come back to us if you reproduce the problem on 11.beeznest.com (access with admin as login and password).
Best regards

**Closed** 2022-12-30 16:25 UTC
Labels: Duplicate / Not a bug / Won't fix
