### ISSUE TITLE
Centralize the login form.

### ISSUE THREAD

**Issue by danillofa** [chamilo/chamilo-lms#2303] opened 2018-01-09 08:15 UTC
How to centralize the login form on the home page?

**Comment by ywarnier** [comment] 2018-01-16 21:54
Please use custom pages. You can find a bit of information on custom pages in the developers guide at https://docs.chamilo.org/en/ (very end of the table of contents).
This is not a bug. Closing. For simple questions, please use our slack channel #chamilo or ask on the forum. Thanks.

**Closed by ywarnier** 2018-01-16 21:54 UTC
Labels: Question / Support
