### ISSUE TITLE
User access overview generates fatal error when searching

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3118] opened 2020-03-10 14:43 UTC
**Describe**
On the admin report for user access overview  : https://11.chamilo.org/main/mySpace/admin_view.php?display=accessoverview

after fiiling up the form click on the generate button and it gives this error : 

`Fatal error: Uncaught Error: Using $this when not in object context in /furanet/sites/11.chamilo.org/web/htdocs/main/inc/lib/formvalidator/Element/DateRangePicker.php:68 Stack trace: #0 /furanet/sites/11.chamilo.org/web/htdocs/main/inc/lib/myspace.lib.php(2904): DateRangePicker::parseDateRange('2019-03-10 / 20...') #1 /furanet/sites/11.chamilo.org/web/htdocs/main/inc/lib/sortable_table.class.php(1130): MySpace::getUserDataAccessTrackingOverview(0, 20, 0, 'ASC', Array) #2 /furanet/sites/11.chamilo.org/web/htdocs/main/inc/lib/sortable_table.class.php(684): SortableTable->get_table_data(0, 20, 0) #3 /furanet/sites/11.chamilo.org/web/htdocs/main/inc/lib/sortable_table.class.php(359): SortableTable->get_table_html() #4 /furanet/sites/11.chamilo.org/web/htdocs/main/inc/lib/myspace.lib.php(2816): SortableTable->return_table() #5 /furanet/sites/11.chamilo.org/web/htdocs/main/mySpace/admin_view.php(64): MySpace::displayTrackingAccessOverView(81, 0, 0) #6 {main} thrown in /furanet/sites/11.chamilo.org/web/htdocs/main/inc/lib/formvalidator/Element/DateRangePicker.php on line 68
`

Reproduced on 11.chamilo.org on the 10/03/2020

**Comment by NicoDucou** [comment] 2020-03-11 09:05
Thanks Julio we can now search in this form, but the result is not correct.

The result table indicates 3574 results what ever the date range is and is only showing 1 result
It tried with dates range 2019-03-11 until 2020-03-11 and also date range of 2020-02-11 until 2020-03-11 and in both case it shows the same result. And if I click on next page it shows the Chamilo menu and all blank below.

![image](https://user-images.githubusercontent.com/6579268/76399916-bfe9fa00-637f-11ea-93e1-a1cc55851b85.png)

**Comment by jmontoyaa** [comment] 2020-03-11 09:14
That's true. So I have a question, I should show : 

1. One row per user? 
2. Show all rows? 

If option 1. is selected, then I have to remove the login date and ip, and I will SUM the clicks and the time connected.

**Comment by Coursenligne** [comment] 2020-03-12 07:29
Just my opinion...
Having somewhere the IP is a very good feature (I mean in professional and secured environment).
If it is possible to leave this it's just the best  :)
Thanks for all guys and  "Bon courage :) "

**Comment by NicoDucou** [comment] 2020-03-13 13:50
As the title of the report says accesses in plural I would say that it is better to show all rows.
So option 2

**Comment by jmontoyaa** [comment] 2020-06-22 11:59
I added some fixes

**Comment by ywarnier** [comment] 2020-07-16 22:12
Assuming this is fixed now. I cannot reproduce the initial error reported.

**Closed by ywarnier** 2020-07-16 22:12 UTC
Labels: Bug
