### ISSUE TITLE
Migration 1.11 to 1.11.2 problem in teacher menu

### ISSUE THREAD

**Issue by mvandenbranden** [chamilo/chamilo-lms#1535] opened 2016-12-07 08:15 UTC
### Expected behavior / Resultado esperado / Résultat attendu
When I upgrade to 1.11.2 I expect that the menu items for the teachers are not changing.

### Actual behavior / Resultado real / Résultat réel
After the migration the menu item "my space" dissapeared for the teachers.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Migrate a 1.11 to 1.11.2, create a user with teacher rights and check the menu.
The problem only happens with a migration. A clean install doesn't have this problem.

**Comment by jmontoyaa** [comment] 2016-12-07 08:30
have you tried to clean the cache? 

/main/admin/archive_cleanup.php

**Comment by mvandenbranden** [comment] 2016-12-07 08:32
Hi Julio,

Yes, we've tried that allready, but with no effect.

**Comment by jmontoyaa** [comment] 2016-12-07 12:45
Do you mean the menu that has this links? 
```
    Create a course
    Add a training session
    Sort courses
    Courses history
    Course catalog
```

**Comment by mvandenbranden** [comment] 2016-12-07 14:03
No, I mean the menu on the campus startpage. The screenshot below is from a clean install and is ok. When logged in as a teacher the button "Mijn ruimte" (my space) is gone in a migrated version 1.11.2

![menu](https://cloud.githubusercontent.com/assets/22000988/20969490/7540f846-bc89-11e6-9051-7bf7a0b1e831.JPG)

**Comment by jderriks** [comment] 2016-12-09 10:36
If it's not in the tabs it will be in the left menu "main navigation" and mySpace is sometimes called "Reporting". May be a translation thing. Of course you can add URLs to main/mySpace yourself.

Note: the "tabs in the header" portal config settings determine if "reporting" is in the tab or in the menu on the left.

**Comment by ywarnier** [comment] 2016-12-23 05:20
I'll close the issue because there has been no answer for 14 days. Just let us know if the issue is still present for you @mvandenbranden .

**Closed by ywarnier** 2016-12-23 05:20 UTC
Labels: More info required, On hold - Can't reproduce
