### ISSUE TITLE
Error en datos personales del alumno.

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#3146] opened 2020-03-29 17:37 UTC
**Describe**
En modo Alumno al ingresar a la Data Personal del Alumno 
main/social/personal_data.php

Sale el siguiente error.
![error](https://user-images.githubusercontent.com/2940509/77855969-b7842280-71b9-11ea-855a-79f57cbe0c0c.png)

`[Sun Mar 29 17:32:23.584691 2020] [php7:error] [pid 17634] [client 181.67.184.121:38037] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Chamilo\\UserBundle\\Entity\\User::setLastLogin() must be an instance of DateTime, null given, called in /var/www/html/src/Chamilo/UserBundle/Repository/UserRepository.php on line 1265 and defined in /var/www/html/src/Chamilo/UserBundle/Entity/User.php:1454\nStack trace:\n#0 /var/www/html/src/Chamilo/UserBundle/Repository/UserRepository.php(1265): Chamilo\\UserBundle\\Entity\\User->setLastLogin(NULL)\n#1 /var/www/html/main/social/personal_data.php(200): Chamilo\\UserBundle\\Repository\\UserRepository->getPersonalDataToJson(6, Array)\n#2 {main}\n  thrown in /var/www/html/src/Chamilo/UserBundle/Entity/User.php on line 1454, referer: https://chamilo.test/user_portal.php`

Dato Adicional:
Este error apare cuando el usuario ingresa por primera vez y no tienen ningún login. y es logueado desde el admin

**Comment by ywarnier** [comment] 2020-06-20 05:42
Duplicate of #3108

**Closed by ywarnier** 2020-06-20 05:42 UTC
