### ISSUE TITLE
Unable to go to next question in test. Chamilo Version 1.11.6.

### ISSUE THREAD

**Issue by akshaybande81** [chamilo/chamilo-lms#2538] opened 2018-05-30 11:06 UTC
Hello,
I am using chamilo version 1.11.6, on Centos 7, when user click next question in chamilo tests, it keeps showing busy and doesn't go to next question. 
Can you help me on that.
Thank you.

**Comment by opensourcecompany** [comment] 2018-05-30 11:34
What does your error log say?

**Comment by akshaybande81** [comment] 2018-05-30 11:40
There is no error log. It shows loader and shows that it is busy and doesn't go to next question. Neither I can submit the test nor go to next question. 
![screenshot from 2018-05-30 17-08-50](https://user-images.githubusercontent.com/13670269/40718065-3180d298-63fe-11e8-9672-b90f119a884c.png)

**Comment by ywarnier** [comment] 2018-05-30 13:48
Does the javascript console show an error?

**Comment by akshaybande81** [comment] 2018-05-31 04:02
Yes. JS console says "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/"

**Comment by ywarnier** [comment] 2018-06-07 00:14
What browser do you use? Does it happen in another browser?

**Comment by rafaelflobel** [comment] 2018-06-07 00:33
Hi,
I have the same problem here. I'm using Ubuntu 16.04.
Firefox and Chrome tested with issue.

**Comment by jmontoyaa** [comment] 2018-06-07 11:32
You should put your portal in "test" mode example (enter with: admin/admin)

https://11.chamilo.org/main/admin/settings.php?search_field=server&category=search_setting

After that, go and try the exercise and check the error that appear. Also check the error log of the server.

Probably this was already fixed in 1.11.x

**Comment by rafaelflobel** [comment] 2018-06-07 18:05
I'm usign 1.11.6 version, some idea about the solution?
Console error: "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/"

**Comment by NicoDucou** [comment] 2018-07-17 11:16
@rafaelflobel Can you try to reproduce the problem on 11.chamilo.org to know if the problem is fixed in the new release of Chamilo coming up shortly ? or if the problem is specific to your installation.

**Comment by ywarnier** [comment] 2018-07-27 03:11
@akshaybande81 can you reproduce it on https://11.chamilo.org/? This helps us define if the issue is with your browser or with your server.

**Comment by ywarnier** [comment] 2018-07-31 17:10
@akshaybande81 we will consider this issue solved in 2 days if you cannot provide any more feedback, as this blocks us from solving the issue.

**Comment by akshaybande81** [comment] 2018-07-31 17:34
I am using Cent Os 7. My browser is firefox. Chamilo verision is 1.11.6. Console log says  "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/". 

I have tried to install same chamilo version with windows os and it worked for that. May be there is problem with browser.

**Comment by ywarnier** [comment] 2018-07-31 18:25
Again, could you try the same operation on https://11.chamilo.org (you don't have to create an account, you can enter with admin/admin) and let us know how it works? This will help us determine if it's a browser or a server issue.

**Comment by akshaybande81** [comment] 2018-07-31 19:03
Thanks. I will try the same operation on  https://11.chamilo.org with cent os 7 and same browser.

**Comment by akshaybande81** [comment] 2018-08-01 12:35
I have tried test on https://11.chamilo.org it works. There must be problem in browser or operating system. 
Thank you.

**Comment by ywarnier** [comment] 2018-08-01 14:48
I believe it is because you have version 1.11.6 and some similar issues have been solved in the development version, which will end up as release 1.11.8 in a few days.
I recommend you download 1.11.8 as soon as it's out and do the install with it. We will probably first release a beta version this week, then the stable at the end of next week.

**Comment by NicoDucou** [comment] 2018-08-01 19:47
So, we can close this task and if you (@akshaybande81 ) reproduce the problem with an installation of 1.11.8 then you could open a new issue.

**Comment by akshaybande81** [comment] 2018-08-02 04:16
Yes. Thank you.

**Closed** 2018-08-02 07:26 UTC
Labels: On hold - Can't reproduce
