### ISSUE TITLE
Problème sur Agenda perso

### ISSUE THREAD

**Issue by Fantome5555** [chamilo/chamilo-lms#2654] opened 2018-09-05 15:52 UTC
J'ai changé mon profil comme Directeur RH.

Je reçois toujours un erreur.

Notice: Undefined variable: sessions in /home/fant/public_html/main/inc/lib/agenda.lib.php on line 3026

Fatal error: Uncaught Error: Unsupported operand types in /home/fant/public_html/main/inc/lib/agenda.lib.php:3026 Stack trace: #0 /home/fant/public_html/main/calendar/agenda_js.php(157): Agenda->displayActions('calendar', NULL) #1 {main} thrown in /home/fant/public_html/main/inc/lib/agenda.lib.php on line 3026

**Comment by ywarnier** [comment] 2018-09-05 18:32
"Unsupported operand types" semble indiquer une version incorrecte de PHP... Quelle est la version de PHP que tu utilises?
La ligne de code:
```
 $sessions = ['0' => get_lang('SelectAnOption')] + $sessions;
```

**Comment by Fantome5555** [comment] 2018-09-05 20:38
C'est Chamilo 1.11.8

"$sessions = ['0' => get_lang('SelectAnOption')] + $sessions;"
Oui c'est ça.

**Comment by ywarnier** [comment] 2018-09-05 22:35
Je parle de la "version de PHP". Voir dans administration -> Système -> Informations du système -> Version de PHP

**Comment by Fantome5555** [comment] 2018-09-05 22:41
Ah desolé c'est 5.6.30 j'ai commis une faute quand je mettais à jour

**Comment by ywarnier** [comment] 2018-09-07 09:34
Et donc... avec 7.*, ça va mieux?

**Comment by yourKatharsis** [comment] 2019-02-08 10:17
I have the same Error with php-7.0.32 and chamilo 1.11.8.
I already checked the user_id (main/calendar/agenda_js.php ( 157)) - its set and not NULL.
And also try another hrm-user.

What else can i do?

**Comment by steven1963** [comment] 2019-02-20 09:44
I have the exact same problem with creating HR users having broken agenda links with the exact same errors and line numbers

**Comment by yourKatharsis** [comment] 2019-03-12 12:37
@ywarnier can we reopen this issue?

**Comment by steven1963** [comment] 2019-03-16 07:22
I have installed both the PHP 5 version and the PHP 7 versions on my Development environment and both installations reflect this bug. I am trying to read through he code starting with account creation for HR Manager then the Login Procedure to see it there is a typo for the creation of the HR Manager not matching what the agenda API is looking for.

**Comment by ywarnier** [comment] 2019-03-16 17:18
Reopening. We need more details though, guys and gals, because so fat we have no context about what whether you have actually tested this on the latest development version or 1.11.8 stable.

**Comment by ywarnier** [comment] 2019-03-16 17:20
Also note that PHP 7.0 *in particular* (not 7.1, 7.2 or 7.3) had a lot of weird behaviour changes, so preferrably try to avoid it (plus it's not supported anymore, anyway: http://php.net/supported-versions.php)

**Comment by steven1963** [comment] 2019-03-18 05:51
this is a consistent issue with all Stable versions when signed in as HR Issue when trying to use the personal agenda for the HR user. I am trying to trace it back. All you have to do is login as a HR manager role and this error shows up in the PHP Logs

Fatal error: Uncaught Error: Unsupported operand types in /home/fant/public_html/main/inc/lib/agenda.lib.php:3026 Stack trace: #0 /home/fant/public_html/main/calendar/agenda_js.php(157): Agenda->displayActions('calendar', NULL) #1 {main} thrown in /home/fant/public_html/main/inc/lib/agenda.lib.php on line 3026

**Comment by steven1963** [comment] 2019-03-18 06:33
I have even gone through the files related to creating an User Role and even coded in a new user roll and the Agenda works fine for the new user role that I created. so it maybe related to the to the View. I am now investigating the Views. I am trying find out how the add the Administration link to the new role and how to manage the admin screen as sample I am trying to limit the access in the administration similar to how the view works for Sessions manager. any pointers to where this is managed would help me possible fix this issue and finish the role inplementation.

**Comment by yourKatharsis** [comment] 2019-04-10 09:53
I just updated php7.0 to 7.2.
This issue still exists.

**Comment by AngelFQC** [comment] 2019-04-10 20:50
Try changing the line

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/agenda.lib.php#L3044

with:
```php
$sessions =  array_merge(['0' => get_lang('SelectAnOption')], $sessions)
```

**Comment by yourKatharsis** [comment] 2019-04-11 07:51
Thanks a lot.
I have access now.
But it still throws an error:
```
Notice: Undefined variable: sessions in /var/www/chamilo/www/main/inc/lib/agenda.lib.php on line 3044

Warning: array_merge(): Argument #2 is not an array in /var/www/chamilo/www/main/inc/lib/agenda.lib.php on line 3044
```

**Comment by steven1963** [comment] 2019-04-12 11:54
does not matter what version of PHP you use I have tried several now and the issue exists

**Comment by ywarnier** [comment] 2019-04-22 20:52
We believe this should be fixed in 1.11.10. I will be releasing a beta version tomorrow so you can test.

**Comment by ywarnier** [comment] 2019-04-27 01:24
We have just published our beta version here https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.10-beta.1
Please check it to make sure whether this issue is fixed, and let us know if it isn't.
We plan to release the stable on the 30th of April, so please don't take too much time doing that. As we can't reproduce this issue, we will consider it fixed if not proven otherwise by the time of the release.
Thanks.

**Comment by bassuma** [comment] 2019-04-27 16:32
OK.
Downloading for test.
Thank you

**Comment by ywarnier** [comment] 2019-04-29 21:14
Any luck reproducing this issue with the beta, anyone?

**Comment by bassuma** [comment] 2019-04-29 21:36
Hi
Unfortunately I can not help.
I changed my profile for HR.
No error message appears.
greetings

**Server vps
OS: CentOS Linux 7.6.1810 (Core)
Version of Chamilo: [1.11.10 Beta 1.]
Version of PHP: [7.2, ...]

**Comment by steven1963** [comment] 2019-04-30 08:57
The Problem of this agenda for HR managers has been resolved in the beta new issue for HR Manager though in beta. in the social network on the "Personal Data" link is going to a blank screen. This also happens with "Learners" the "Admin" accounts works fine

**Comment by bassuma** [comment] 2019-04-30 13:13
@steven1963
Hello.
I do not know if that helps.
Switch to test server.
See if the white page will show the problem warning.
Go in administration;
Server Type:
* Test Server

Greetings

**Comment by bassuma** [comment] 2019-04-30 13:27
Hi
I went to 11.chamilo.org.
I created an admin profile.
then I switched to HR.
I went to social network.
And I clicked on "Personal data"
Shows this.
img
greetings
![RH](https://user-images.githubusercontent.com/25286516/56964985-968ef980-6b32-11e9-923c-c4de8bee63bc.png)

**Comment by ywarnier** [comment] 2019-05-03 23:20
This last commit fixed the "notice" issue. That was good reporting. Thanks.

**Closed by ywarnier** 2019-05-03 23:20 UTC
Labels: On hold - Can't reproduce
