### ISSUE TITLE
fillSurvey.php "Show profile form" updates all users

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#2331] opened 2018-01-16 18:30 UTC
### Current behavior / Resultado actual / Résultat actuel
If you enable the "Show profile form" and update any of the allowed fields fields it will apply it to all users in the user table.

```
                $sql = "UPDATE $table_user SET";
                $update = false;
                $allowedFields = [
                    'firstname',
                    'lastname',
                    'official_code',
                    'email',
                    'phone',
                    'language'
                ];
                foreach ($user_data as $key => $value) {
                    if (in_array($key, $allowedFields)) {
                        $sql .= " $key = '".Database :: escape_string($value)."',";
                        $update = true;
                    }
                }
                // Remove trailing , from the query we have so far
                $sql = rtrim($sql, ',');
                if ($update) {
                    Database::query($sql);
                }
```

### Expected behavior / Resultado esperado / Résultat attendu

It should only apply to the user currently filling the survey

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Create a survey with the "Show profile form" option enabled share link to students have students press Next on the profile page of the survey. (No need to change anything).

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Branch 1.11x has this issue (tried it on 11.chamilo.org eveybody is now called Test 1-2-1-2)

**Comment by ywarnier** [comment] 2018-01-16 18:40
Ups :-)
We'll have a look at that.

**Comment by ywarnier** [comment] 2018-01-16 19:19
I have to admit, doing that on 11.chamilo.org has a funny result :-)

**Comment by meuhland** [comment] 2018-01-16 19:21
It was even more funnier on our deployment
mysql> select count(*) from user;
+----------+
| count(*) |
+----------+
|    17789 |
+----------+

Fun times indeed.... not

**Comment by ywarnier** [comment] 2018-01-16 19:25
Sorry to hear that. You have a nice-sized portal though. Where is that?

**Comment by ywarnier** [comment] 2018-01-16 19:26
Do you still have the invitation link for the survey on 11.chamilo.org? (so I don't have to create a new one)

**Comment by meuhland** [comment] 2018-01-16 19:28
https://11.chamilo.org/main/survey/fillsurvey.php?course=TESTCEMEQLPG&invitationcode=auto&scode=test&id_session=0 there you go there is also a weird issue that the post action has html entities in it (only sometimes haven't figured out why that is)

**Comment by ywarnier** [comment] 2018-01-16 19:42
I actually never manage to go through (I always have html entities). Checking...

**Comment by meuhland** [comment] 2018-01-16 19:47
![9b41de5c](https://user-images.githubusercontent.com/6123610/35008814-d12a4000-facb-11e7-8220-b543ca8b36ac.PNG)

Was the source that I tracked down on my production environment... To be sure it ran on 11.chamilo.org a fixed it in Developer Mode of my browser.

**Comment by ywarnier** [comment] 2018-01-16 20:02
Yeah... it's just unlikely that normal users would do that :-)

**Comment by meuhland** [comment] 2018-01-16 20:03
Yeah but like I said it works just fine on my production server not sure what broke it between 1.11.2 and current.

**Comment by ywarnier** [comment] 2018-01-16 20:12
The loosing of user_id has been lost unintentionally in a much bigger commit: https://github.com/chamilo/chamilo-lms/commit/327c07aae16358d2b19160dc09a9e0bb492f9fd5#diff-79db2518038e753699bd4a0b9abdde1eL523 (in May 2015).

**Comment by meuhland** [comment] 2018-01-16 20:23
Awesome but wouldn't that code need to be updated to use the UserManager as opposed to a straight SQL query?

**Comment by ywarnier** [comment] 2018-01-16 20:25
Yes, but that's not a topic for right before a release. Feel free to contribute by sending clean-up pull requests. After 1.11.6 (I'd really like to release it this week), we're going to go for Chamilo 2.0 and start with a few background changes. Then we'll have about 5 months to improve code quality, but we all have better things to do with our free time than clean up code.

**Comment by meuhland** [comment] 2018-01-16 20:27
I totally agree with this statement!

**Comment by ywarnier** [comment] 2018-01-16 21:06
OK, with these 2 commits, the issue should be gone. 11.chamilo.org will be automatically updated in about 20 minutes for testing.

**Comment by ywarnier** [comment] 2018-01-17 19:24
Tests look good. I cannot reproduce the issue. Closing.

**Closed by ywarnier** 2018-01-17 19:24 UTC
Labels: Bug, Requires testing/validation
