### ISSUE TITLE
1.11.2 Assignments - Upload package corrections

### ISSUE THREAD

**Issue by djoshy** [chamilo/chamilo-lms#1520] opened 2016-11-24 10:45 UTC
### Expected behavior / Resultado esperado / Résultat attendu
A list of uploaded files from a zip package
### Actual behavior / Resultado real / Résultat réel
No files are uploaded (but a message says "uploaded")
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
When I try to send a zip file (or other format) with the button "Upload package corrections" in Assignments tool, I have the message "uploaded" but no file is displayed in the list.

Maybe I use this function incorrectly or I doesn't understand its use (its translation in French is "Envoyer un paquet de travaux") ...

Tested also on: https://campus.chamilo.org (the button is called "upload corrections") with the same issue

**Comment by ywarnier** [comment] 2016-12-23 05:22
@jmontoyaa I'm assigning this to you because I believe it is more a question of use than an issue. Could you check if the behaviour described is the intended behaviour for the assignments tool?

**Comment by ywarnier** [comment] 2017-03-22 17:58
Won't be able to check this in this version.

**Comment by NicoDucou** [comment] 2018-03-05 15:45
I just check here, and the procedure is as follow : 
The profesor create an assignment.
The students send their files.
The profesor get back to the assignment and click on "Upload package corrections" which in my test case is this page :  https://11.chamilo.org/main/work/upload_corrections.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&id=72
On this page there is a message indicating : "First you have to download the corrections here . After that you have to unzip that file and edit the files as you wanted without changing the file names. Then create a zip file with those modified files and upload it in this form."
in french it's : "Veuillez d'abord télécharger les corrections ici puis les décompresser et éditer les fichiers sans changer leurs noms. Ensuite, créez un fichier zip avec les fichiers modifiés et téléchargez-le vers le serveur sous cette forme."

I just follow this procedure and all went fine, the student (amann/amann) could get its correction on this page : https://11.chamilo.org/main/work/view.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&id=136

@djoshy can you try and let us know if every thing is fine and if so close the task.

**Closed** 2020-12-04 10:23 UTC
Labels: Question / Support, wontfix
