### ISSUE TITLE
location nginx could be enhanced

### ISSUE THREAD

**Issue by floriangasc** [chamilo/chamilo-lms#4396] opened 2022-09-23 19:52 UTC
**Describe**
I am french, sorry for my engilsh and i used nginx, and there is wrong nginx location config for tabs «suivi». I follow this page https://11.chamilo.org/documentation/installation_guide_fr_FR.html

**To Reproduce**
1. logged in admin
2. click on «suivi» and header and get an HTTP error 
**Expected behavior**
display page

**Screenshots**

**Server
 - OS: [e.g. Linux Ubuntu 18.04]
 - Server nginx.

**How to Fix
most simple way is to replace 

```
location /main {
   rewrite ^/main/admin/$ /main/admin/index.php last;
}
```

by this

```
location /main {
    rewrite ^/main/([^/]+)/?$ /main/$1/index.php last;
}
```

Tested in real life

another way is to make a link /admin/mySpace/index.php instead of /admin/mySpace

**Comment by ywarnier** [comment] 2023-01-09 23:44
@floriangasc 
Sorry for the delay answering and thanks for reporting.
Just out of curiosity, because I cannot reproduce the issue you reported : do you have a line `index index.php;` somewhere in your `server` block ?
I know it's not stated in https://11.chamilo.org/documentation/installation_guide_fr_FR.html, but I want to make sure that this is the issue.
If you don't have it, I suggest you add it as it's a good way of avoiding the issue you had and others.
If so, could you quickly test it and confirm it works with that additional clause and without modifying the `location /main` block ?
I will add it to the documentation to avoid other issues I might not have foreseen.

**Comment by ywarnier** [comment] 2023-01-09 23:54
Nevermind my previous (deleted) message. I could reproduce the issue in the end.

**Comment by ywarnier** [comment] 2023-01-10 00:31
Fixed by https://github.com/chamilo/chamilo-lms/commit/25421be09067e863bebb9d9b49f670e8a3505c08
Thanks for your report and contribution

**Closed by ywarnier** 2023-01-10 00:31 UTC
Labels: Enhancement

**Comment by floriangasc** [comment] 2023-01-11 19:43
@ywarnier 

You're welcome. Glad I could help. 

Best wishes.
