### ISSUE TITLE
Resume a test on last question automatically end the test

### ISSUE THREAD

**Issue by baelmyhu** [chamilo/chamilo-lms#1837] opened 2017-04-13 13:39 UTC
### Current behavior / Resultado actual / Résultat actuel
On a test with several questions one on a page, I display on each question with the button "next question" and quit the test.
I run the test again, i should be able to resume the test, but the page I see is the test finished, and I see my score and the test has been automatically ended.

### Expected behavior / Resultado esperado / Résultat attendu
I should be able to resume the test

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a test with 2 questions.
Run the test and go on the 2 questions without ending the test.
Quit the test.
Go on the test again.
The test has been automatically ended.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11 on unstable.chamilo.org

**Comment by jmontoyaa** [comment] 2017-05-18 07:52
I tried locally with latest code 1.11.x I cannot reproduce the error.
I can resume an exercise if "all questions in one page" or "one question per page".
Please provide an example in  http://1.11.chamilo.org/

**Comment by ywarnier** [comment] 2017-05-23 04:29
Missing feedback here. Closing.

**Closed by ywarnier** 2017-05-23 04:29 UTC
Labels: Bug, More info required, On hold - Can't reproduce
