### ISSUE TITLE
Missing icons in the action bar

### ISSUE THREAD

**Issue by sercon** [chamilo/chamilo-lms#1850] opened 2017-04-19 12:20 UTC
### Current behavior / Resultado actual / Résultat actuel
When opening pages with a visible action bar, Some items show an empty box.
![image](https://cloud.githubusercontent.com/assets/12449415/25178791/932285c8-2507-11e7-8477-3d264e94cd21.png)

### Expected behavior / Resultado esperado / Résultat attendu
On https://campus.chamilo.org/main/newscorm/lp_controller.php?cidReq=TESTXOP&id_session=0&gidReq=0&gradebook=0&origin= it shows as it should be
![image](https://cloud.githubusercontent.com/assets/12449415/25178834/c3bf60f2-2507-11e7-862d-21b431983b90.png)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1/ Downloaded the latest version (13_3_2_ZeroXIII.exe) of the uniserver WAMP solution from https://sourceforge.net/projects/miniserver/files/latest/download?source=files. 
Uses php7.1.1 on Apache 2.4.17 with Mysql 5.6.35.0
2/ extract the above exe and start UniController.exe. Enable PHP Version 7.1.1 with necessary modules.
3/ download the latest chamilo version chamilo-lms-1.11.2.zip (Release date: 01/11/2016) from https://chamilo.org/chamilo-lms/#downloads and extract it to the UniServerZ\www\chamilo directory
4/ useUniController.exe to start mysql and apache
5/ open http://localhost/chamilo/ in Firefox 52.0.2 and run the chamilo setup connecting to mysql on localhost
6/ Login with the in step 5 created admin user and password
7/ Create a new course via http://localhost/chamilo/main/admin/course_add.php and 'fill with demo content'
8/ Open the course list http://localhost/chamilo/main/admin/course_list.php
Already there is an icon missing in the action bar
![image](https://cloud.githubusercontent.com/assets/12449415/25179468/58224348-250a-11e7-8afb-d0d48387c195.png)
Inspecting the button shows there is no code for an image icon
![image](https://cloud.githubusercontent.com/assets/12449415/25179507/7f433db0-250a-11e7-9e57-a2372d2ecdc4.png)
9/ Open the newly created course by clicking on its name http://localhost/chamilo/courses/EXAMPLE/index.php
10/ Click on the icon for "learning path" URL http://localhost/chamilo/main/lp/lp_controller.php?cidReq=EXAMPLE&id_session=0&gidReq=0&gradebook=0&origin=
11/ You now have a visible action bar with only the first icon visible and two empty boxes.
![image](https://cloud.githubusercontent.com/assets/12449415/25179620/fb21ec10-250a-11e7-9d5e-32522517c389.png)
With inspect element, we see that indeed the first box has a valid img, the other two have not.
![image](https://cloud.githubusercontent.com/assets/12449415/25179663/2710916e-250b-11e7-9fa8-2887d79fbbae.png)
Since the first icon is visible, i suppose it is not a question of wrong path names or rewrites.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Tested with versions chamilo-lms-1.11.0 and chamilo-lms-1.11.2.zip.

**Comment by jmontoyaa** [comment] 2017-04-19 12:32
I think this was already fixed for next version. You should trying the latest 1.11.x code.

**Comment by sercon** [comment] 2017-04-19 12:58
Downloaded zip from https://github.com/chamilo/chamilo-lms/tree/1.11.x and upgraded existing install.
Works like breeze.
Thx for the (very) quick response :-)

**Comment by ywarnier** [comment] 2017-04-19 13:40
Additionally, we have reservations on supporting 7.1 for now (although I'm using it locally), as we haven't reviewed the whole system yet, and automated tests were failing not so long ago with 7.1.

**Comment by sercon** [comment] 2017-04-20 09:01
Since the upgrade to https://github.com/chamilo/chamilo-lms/tree/1.11.x there are problems working with SCORM files. The same files that worked flawlessly in the chamilo-lms-1.11.2 version, now give errors related to doctrine like:

Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded. in D:\Apps\WAMP\www\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54 Stack trace: #0 D:\Apps\WAMP\www\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 D:\Apps\WAMP\www\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation() #2 D:\Apps\WAMP\www\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations() #3 D:\Apps\WAMP\www\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationReader.php(226): Doctrine\Common\Annotat in D:\Apps\WAMP\www\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54

I've tried with PHP Version 7.0.15: same problem. What version of php is advised ?
I've tried updating composer using the command php -f composer.phar update --profile -vvv
The problem persists. 

Thx.

**Comment by sercon** [comment] 2017-04-20 09:41
We get the same doctrine error when trying to delete an existing scorm/learnpath. When pressing the back button after the error, the path is deleted.
![image](https://cloud.githubusercontent.com/assets/12449415/25224286/38c35898-25be-11e7-850b-bab0d546bc52.png)

**Comment by sercon** [comment] 2017-04-20 13:03
Might be the same as issue https://github.com/chamilo/chamilo-lms/issues/1529 ?

What version do you recommend to use for the moment ?
The latest 1.11.x code seems to have a problem with Doctrine / File upload and the latest stable has a problem with the (action) icons.

**Comment by ywarnier** [comment] 2017-04-20 20:03
When downloading a development version, you *have to* update all the dependencies with `composer update`. Did you do this? Because your error messages is relatively symptomatic of a non-updated list of dependencies.

**Comment by sercon** [comment] 2017-04-21 07:46
Yes we did. Ran it again to be sure. Output:
>php -f composer.phar update
> Chamilo\CoreBundle\Composer\ScriptHandler::deleteOldFilesFrom19x
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Chamilo\CoreBundle\Composer\ScriptHandler::dumpCssFiles

Tried deleting a learn path, but it gives the same error:
Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded. in C:\inetpub\wwwroot\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54 Stack trace: #0 C:\inetpub\wwwroot\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(734): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 C:\inetpub\wwwroot\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(663): Doctrine\Common\Annotations\DocParser->Annotation() #2 C:\inetpub\wwwroot\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations() #3 C:\inetpub\wwwroot\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationReader.php(250): Doctrine\Common\Annotations\DocParser->parse('/**\n in C:\inetpub\wwwroot\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54 

I could try emptying the vendor directory and rebuilding it ?

**Comment by sercon** [comment] 2017-04-21 09:07
I just removed the vendor directory and ran a composer update to repopulate. 
The same doctrine exception is thrown on uploading a scorm or removing a learnpath.

**Comment by ywarnier** [comment] 2017-04-21 18:10
Yes, removing the vendor/ directory can help. Sorry that didn't work in your case.

I have PHP 7.1 here and I don't see the problem (I just tried removing vendor, doing composer update and creating+deleting a learning path: all good). In short: Cannot reproduce.

**Comment by ywarnier** [comment] 2017-04-21 18:14
You can try deleting vendor *and* composer.lock *and* clearing your composer cache with "composer clear-cache" and *then* composer update... (not sure, just trying to give more hints here on what might not be working for you).

**Comment by sercon** [comment] 2017-04-24 15:14
Done that. I even re-downloaded the latest build and started from scratch: download & extract zip file, composer update (absolutely necessary, since the  https://github.com/chamilo/chamilo-lms/tree/1.11.x  download does not contain a vendor directory). Logged in. Same error when deleting learnpath or uploading scorm file. Even tried on other pc: same error. Also tried on an iis server where the stable version runs without errors (but also without icons :-) and it gives the same error. Very strange that it cannot be reproduced. Any chance of getting a zip with the webtree you use ?

Thx.

**Comment by jderriks** [comment] 2017-04-24 22:57
On Windows I cannot get the system installed beacause of doctrine errors. On mac and linux it works.
I think this is the same problem.
Can somenone explain this rrror:
![knipsel](https://cloud.githubusercontent.com/assets/1659604/25362075/12599b1c-2952-11e7-86d9-cd3e17054a74.PNG)

**Comment by ywarnier** [comment] 2017-04-24 23:16
Well the issue probably boils down to a requirement in the Annotation component of Doctrine (which allows us to design the ORM structure more clearly, as explained in http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html). This should be fixed (I hope) when we release the first beta of 1.11.4 (which shouldn't be too long from now, as we're already late of about 60 days), because dependencies come pre-loaded in beta packages (so you don't have the issues of them not being inside vendor, which I guess is the issue here).

**Comment by ywarnier** [comment] 2017-04-24 23:17
I hope to be releasing a beta package around the 3rd of May.

**Comment by jderriks** [comment] 2017-04-25 16:33
So if 1.11.x is not stable, what is the latest stable branch to use?

**Comment by aragonc** [comment] 2017-04-26 16:39
I'm viewing the icons on the bar in normal way 
![icons](https://cloud.githubusercontent.com/assets/2940509/25445713/b6441ea0-2a74-11e7-8da1-5ae6a761d8f9.png)

**Comment by jderriks** [comment] 2017-04-27 11:24
Try run "composer update" and do a fresh install first.

Testing Chamilo is like shooting on a moving target every time you do "composer update".

To fix the doctrine annotation exception I think the composer dependency versions must be changed but I don't know what versions works. **A quick workaround to fix the install and exception errors is to remove the @Assert lines in the comments of src/Chamilo/CoreBundle/Entity/Course.php**. Then installation can continue.

Then testing can continue and clicking on the middle icon of the learning path tool thows up another error:
`Fatal error: Uncaught exception 'Exception' with message 'Class 'DatePicker' does not exist. ' in C:\xampp\htdocs\chamilogit\main\inc\lib\pear\HTML\QuickForm.php:501 Stack trace: #0 C:\xampp\htdocs\chamilogit\main\inc\lib\pear\HTML\QuickForm.php(564): HTML_QuickForm->_loadElement('addElement', 'DatePicker', Array) #1 C:\xampp\htdocs\chamilogit\main\inc\lib\formvalidator\FormValidator.class.php(224): HTML_QuickForm->addElement('DatePicker', 'publicated_on', 'Publication dat...', Array) #2 C:\xampp\htdocs\chamilogit\main\lp\lp_add.php(116): FormValidator->addDatePicker('publicated_on', 'Publication dat...') #3 C:\xampp\htdocs\chamilogit\main\lp\lp_controller.php(595): require('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\chamilogit\main\inc\lib\pear\HTML\QuickForm.php on line 501`

o, o, Chamilo...

I have added the "composer show" report which is different from a working chamilo version.


[comshowBAD.txt](https://github.com/chamilo/chamilo-lms/files/961394/comshowBAD.txt)

**Comment by jmontoyaa** [comment] 2017-04-27 12:00
I tried in my local pc with php 7.1 deleting vendor and composer.lock then composer update. And I have no problem.

I tried also the same in 1.11.chamilo.org (PHP 5.5) and I don't see any composer error .

Check that your PHP CLI and PHP/Apache server are the same version.
Also update you should update your composer file.

**Comment by jderriks** [comment] 2017-04-27 12:07
Ok, I will check php versions. Note: currently testing on Windows. On Mac and Linux there are less problems.

I also found that the Datepicker problem is already mentioned here:
https://github.com/chamilo/chamilo-lms/issues/1694

**Comment by jmontoyaa** [comment] 2017-04-27 12:10
Sadly I don't have windows dev environment to test this.

**Comment by jderriks** [comment] 2017-04-28 10:53
On Linux and Mac the doctrine Assert errors are gone but the Datepicker problem remains when clicking the middle icon when creating a new learning path.

**Comment by jderriks** [comment] 2017-05-02 14:17
Is fixed now - can be closed.

**Closed** 2017-05-15 03:58 UTC
Labels: Bug

**Comment by ywarnier** [comment] 2017-06-01 16:04
We released the stable version yesterday but it seems the "Annotation" issue is still there. We are tracking it in issue #1997
