### ISSUE TITLE
Special Characters like accentuation marks breaks announcement titles on e-mails

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#2217] opened 2017-11-07 11:57 UTC
### Current behavior / Resultado actual / Résultat actuel
If The course title  or the title of the announcement  contains special characters like ç ã ê í à, when the notification e-mail is sent the subject is blank (no subject).

Maybe some variable escape error, or UTF-8 to ISO error..... 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a course ie. "Introdução"
Send a announcement to a student. (nothing on subject)
Now try to rename course to "Introducao". (email is ok)
Now try another announcement  with any word with accentuation i.e. "Introdução" (nothing on subject)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6-dev and 1.11.0

**Comment by marshel** [comment] 2017-11-07 12:28
On the DB side, the title is recorded correctly. So it must be an error on the mail function.

**Comment by jmontoyaa** [comment] 2017-11-14 14:28
I cannot reproduce the error, can you please try here?

http://11.chamilo.org/ admin/admin

**Comment by marshel** [comment] 2017-11-14 15:44
On your install there is no problem. 

Things I Though about that could cause it:
- DB collage?
- Chamilo config file?
- mail server? postfix configuration? dovecot?
- php7 or apache configuration?
- some linux package misconfigured or missing

Would it be possible to someone (beeznest for example) attach or PM to me with the list of packages on its system, php.ini/php extensions and a the apache setting so I would compare the config?
I'm actually using latest ubuntu LTS (xenial) on my servers with LAMP with https plus webmin and ssh.

My workaround was change the translation on my system so the titles aren't using special characters.

**Comment by ywarnier** [comment] 2017-12-14 15:23
Hi @marshel,
This is the list of packages on 11.chamilo.org (Debian Jessie):
```
ii  php-apcu                         5.1.8+4.0.11-1+0~20170825111220.1+jessie~1.gbpcbae00              amd64        APC User Cache for PHP
ii  php-apcu-bc                      1.0.3-5+0~20170825111428.1+jessie~1.gbpe777a0                     amd64        APCu Backwards Compatibility Module
ii  php-cli                          1:7.1+55+0~20170905045103.3+jessie~1.gbp8493dd                    all          command-line interpreter for the PHP scripting language (default)
ii  php-common                       1:55+0~20170905045103.3+jessie~1.gbp8493dd                        all          Common files for PHP packages
ii  php-geoip                        1.1.1-1+0~20170825111212.1+jessie~1.gbp2bf964                     amd64        GeoIP module for PHP
ii  php-pear                         1:1.10.5+submodules+notgz-1+0~20170904061701.3+jessie~1.gbpe356ca all          PEAR Base System
ii  php7.1                           7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.1-cli                       7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        command-line interpreter for the PHP scripting language
ii  php7.1-common                    7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        documentation, examples and common module for PHP
ii  php7.1-curl                      7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        CURL module for PHP
ii  php7.1-dev                       7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        Files for PHP7.1 module development
ii  php7.1-fpm                       7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.1-gd                        7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        GD module for PHP
ii  php7.1-intl                      7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        Internationalisation module for PHP
ii  php7.1-json                      7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        JSON module for PHP
ii  php7.1-mbstring                  7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        MBSTRING module for PHP
ii  php7.1-mcrypt                    7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        libmcrypt module for PHP
ii  php7.1-mysql                     7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        MySQL module for PHP
ii  php7.1-opcache                   7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        Zend OpCache module for PHP
ii  php7.1-readline                  7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        readline module for PHP
ii  php7.1-xml                       7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.1-zip                       7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3                   amd64        Zip module for PHP
```

In this case we use Nginx + PHP-FPM, but that should not have any impact on codification.

I do remember, however, that we had an issue like this in the past for a portal in Brasil (I cannot find it anymore in our systems), but that was *only* related to the name of the portal (the rest of the e-mail topic could include accents). Could you try that, changing the name of your portal to something without accents?

**Comment by ywarnier** [comment] 2018-03-09 14:33
No feedback provided in weeks. Closing.

**Closed by ywarnier** 2018-03-09 14:33 UTC
Labels: On hold - Can't reproduce
