### ISSUE TITLE
The Term & Conditions is not showing in the page of registration

### ISSUE THREAD

**Issue by mesoshqip** [chamilo/chamilo-lms#3179] opened 2020-04-10 23:36 UTC
The terms and conditions is showing like the comments below:
https://github.com/chamilo/chamilo-lms/issues/2244#issuecomment-352710567

In /main/admin/configure_inscription.php is showing well (see the picture)
![main_admin_configure_inscription](https://user-images.githubusercontent.com/59404111/79029354-55052c00-7b94-11ea-9c74-df3d98c879c2.png)

but in the registration form /main/auth/inscription.php is showing after the user is registered and is doing the first login.
![main_auth_inscription](https://user-images.githubusercontent.com/59404111/79029367-61898480-7b94-11ea-8169-8c305270f4b2.png)

 - OS:  Linux Ubuntu 18.04
 - The version of Chamilo: 1.11.10
 - The version of PHP: 7.2,
I checked the files explained in the issue "Fix terms and redirection see #2244"
are correct.

What can I do?

**Comment by ywarnier** [comment] 2020-06-22 21:41
@NicoDucou can you give us some feedback on whether the current behaviour is the expected behaviour.

**Comment by ywarnier** [comment] 2020-07-02 22:12
@NicoDucou ping

**Comment by NicoDucou** [comment] 2020-07-03 12:57
Hi @mesoshqip 

On the administration page of terms and condition (main/admin/legal_add.php) you have 2 options :
*  HTML
* Page Link

![image](https://user-images.githubusercontent.com/6579268/86471072-ee2f8300-bd3c-11ea-81fb-6e6fdbdbdbe6.png)

If you select HTML then the text will appear directly on the page for the user to accept.
If you select page link then there will be a sentence as on your screenshot with a link to the page presenting the terms and conditions.

In the GDPR directive it is indicated that the user should accept the terms and condition with an active action, so the sentence with the link with a check box at the begining is better in this case because the user needs to click on the check box (so do an active action) to then validate.

I hope this answers your question.
If you have more question just ask other wise in 7 days we will close this task.

Best regards

**Comment by NicoDucou** [comment] 2020-07-03 13:04
I just realise that the question was about the fact that on the registration configuration it appears on the registration form whereas on Chamilo it is separated. The registration form is one and then at first login there is the GDPR acceptance.

The terms and conditions check box should no appear on /main/admin/configure_inscription.php because it generates confusion.

**Comment by NicoDucou** [comment] 2020-07-03 13:05
Julio the terms and conditions should no appear on /main/admin/configure_inscription.php

**Comment by NicoDucou** [comment] 2020-07-06 07:09
It's all good for me, just tested on https://11.chamilo.org/
It is now the same everywhere. The terms and conditions do not appears on the registration form nor on the configuration of the registration form.
@mesoshqip I let you confirm it is all good now.
Best regards

**Closed** 2020-07-19 23:38 UTC
Labels: Bug, Requires testing/validation
