### ISSUE TITLE
Installation on Maria DB Cluster Galera. Error with auto-increment

### ISSUE THREAD

**Issue by baelmyhu** [chamilo/chamilo-lms#2010] opened 2017-06-07 15:36 UTC
### Current behavior / Resultado actual / Résultat actuel
When you install Chamilo 1.11.2 on Maria DB Cluster Galera, you got error

Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`chamilo1112`.`access_url_rel_user`, CONSTRAINT `FK_8557426373444FD5` FOREIGN KEY (`access_url_id`) REFERENCES `access_url` (`id`)) 

When you look at table user, the first user (admin) gets id=3 (or 4, for exemple), and not 1 as expected.
In Maria DB Cluster Galera, to avoid conflict auto-increment doesnt start at 1, and its step isn't 1. 
(see  http://codership.blogspot.fr/2009/02/managing-auto-increments-with-multi.html)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Tested on 1.11.2

**Comment by ywarnier** [comment] 2017-12-12 17:19
I'm trying to locate code that would generate this, but in 1.11.x the access_url_rel_user table is created but not filled upon creation. It's only later in the installation process (install.lib.php line 2867) that a user gets created and an insert in the access_url_rel_user table is executed.
This calls UserManager::create_user() which, if no access_url is set, takes access_url = 1.

From your error message, it looks like the issue is *not* the user id (admin), but rather the access_url ID (because it says "FOREIGN KEY (access_url_id) REFERENCES access_url (id))".

This, in fact, makes it easier to solve, as it means that UserManager::create_user() needs to be updated to use access_url as the first row instead of "1"

**Comment by ywarnier** [comment] 2017-12-12 17:38
This commit (a bit long and adding a new entity repository) should fix your issue. I'm not sure you can test it anymore, but if you can, great! If not, then I'll consider the issue closed by the end of the week.

**Comment by ywarnier** [comment] 2017-12-12 17:39
If you test that on an existing repository of 1.11.x, please make sure you launch at least a `composer install` as the autoloader has to be updated to include the new AccessUrlRepository

**Comment by ywarnier** [comment] 2017-12-14 15:46
I think this should work anyway. I'll close the task for now but don't hesitate to re-open if you see something wrong in your next tests.

**Closed by ywarnier** 2017-12-14 15:46 UTC
Labels: Enhancement, Requires testing/validation
