### ISSUE TITLE
LDAP Connection Error

### ISSUE THREAD

**Issue by farhadbarati** [chamilo/chamilo-lms#2983] opened 2019-09-01 11:20 UTC
i have a domain controller (windows server 2012 R2) and filled $exldap_config like below:

$extldap_config = array(
  //base dommain string
  'base_dn' => 'DC=example,DC=local',
  //admin distinguished name
  'admin_dn' => 'CN=john,OU=r&d,DC=example,DC=local',
  //admin password
  'admin_password' => '123456789',
  //ldap host
  'host' => array('172.16.8.5'),
  // filter
//  'filter' => '', // no () arround the string
  //'port' => '389'
  //protocl version (2 or 3)
  'protocol_version' => 3,
  // set this to 0 to connect to AD server
  'referrals' => 0,
  //String used to search the user in ldap. %username will ber replaced by the username.
  //See extldap_get_user_search_string() function below
//  'user_search' => 'sAMAccountName=%username%',  // no () arround the string
  'user_search' => 'uid=%username%',  // no () arround the string
  //encoding used in ldap (most common are UTF-8 and ISO-8859-1
  'encoding' => 'UTF-8',
  //Set to true if user info have to be update at each login
  'update_userinfo' => true
);

and uncomment these lines:

$extAuthSource["extldap"]["login"] = $_configuration['root_sys']."main/auth/external_login/login.ldap.php";
$extAuthSource["extldap"]["newUser"] = $_configuration['root_sys']."main/auth/external_login/newUser.ldap.php";

but when i try to validate users, it show LDAP connection error.
![image](https://user-images.githubusercontent.com/47290937/64075639-01fafa80-ccd0-11e9-928f-00401883ab72.png)

where is ldap log and what's wrong with my configuration?
by the way i can telnet to 389 port on Active Directory server in Chamilo server.

**Comment by farhadbarati** [comment] 2019-09-02 03:16
when i uncomment 'port' => '389' i'll get HTTP 500 error!!!

**Comment by ywarnier** [comment] 2020-06-20 02:13
Hi @farhadbarati 
Sorry for the delay answering.

LDAP is a bit of a pain to configure, but we try to improve the LDAP scripts in each new version, so chances are it will already be a bit clearer in 1.11.12 to be published in a few weeks.

In any case, I would try version 2 of LDAP just in case.

You asked where the logs are, for LDAP. There isn't really a specific location for the logs. You should know, however, that the same main/auth/external_login/login.ldap.php that is included through your change in configuration.php has a "$debug" variable set to false at the very beginning. If you change this variable to true, your PHP error log should fill with a lot of interesting feedback info on what's going on with the LDAP connection.

**Comment by ywarnier** [comment] 2020-06-20 02:14
I'm closing this issue because we have several LDAP setups working and it's usually an issue with the domain or the protocol, so it's more a matter of adjusting the setting, not a bug.

**Closed by ywarnier** 2020-06-20 02:13 UTC
