### ISSUE TITLE
Learning Path for Groups not visible if "Subscribe groups into category" is selected

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3524] opened 2020-09-17 10:11 UTC
I have Course Math that contains students separted into two groups Group A and Group B

I created a Category under learningpath section called "Group A LA"

I added user for this category based on "Subscribe groups into category" and chose Group A

I created a learningpath and chose its category to be "Group A LA".

By now students in Group A should be able to see this learningpath but that is not the case none is able to see the learningpath.

On the other hand if i chose "Subscribe users to category" for the category "Group A LA" and added one student from Group A for example for testing, this student was able to see the learningpath with no issues. 

So "Subscribe groups into category" is not working
"Subscribe users to category" is working

Is there a way to fix this.

I have recreated the problem at https://11.chamilo.org/main/lp/lp_controller.php?action=list&cidReq=MACCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&&isStudentView=false

But the problem is not there. Everything is working fine.

**Comment by ywarnier** [comment] 2020-11-20 22:03
@aelalfey it is likely this is solved in version 1.11.14 to be published this month. I'm closing this issue because it cannot be reproduced in the latest code build (11.chamilo.org) but feel free to reopen if it persists after an update to 1.11.14.

**Closed by ywarnier** 2020-11-20 22:03 UTC
