### ISSUE TITLE
Incorrect time in Thematic Advance

### ISSUE THREAD

**Issue by rejuvenator** [chamilo/chamilo-lms#3008] opened 2019-10-05 15:31 UTC
**Describe**
The time displayed in Course Progress/Thematic Advance (and taken from Attendances) is wrong - it displays Greenwich Mean Time instead of my local time. Timezone on my server is set up correctly, and also the correct time is displayed elsewhere in the course, including Attendances and even the list of dates/times on the _Edit thematic advance_ page.

**To Reproduce**
1. Attendances: Create a new attendance list (repeated dates)
2. In Course Progress, add new thematic section, 
3. Create new thematic advance and select one of the dates.
4. Confirm and see different time in Course Progress/Thematic Advance (assuming you're not actually using GMT as your system time)

**Expected behavior**
Local (server) time displayed instead of GMT

**Desktop (please complete the following information):**
 - OS: Manjaro 18.1.0 KDE
 - Browser: Vivaldi / Opera / Chrome

**Server**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo 1.11.10
 - Version of PHP: 7.3

**Comment by ywarnier** [comment] 2019-10-06 17:04
Just to cut a bit the testing time... what timezone do you use?
It seems like the code of the thematic advance tool in general is local-time "aware", so we will need to dive deeper to understand the issue for you.
https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/course_progress/thematic_advance.php#L174

**Comment by rejuvenator** [comment] 2019-10-06 19:12
I use Central European time (Warsaw). The time shown in the thematic advance column is two hours earlier, which I think is GMT.

**Comment by ywarnier** [comment] 2020-07-09 22:25
Internal note: This would be in php.ini
```
date.timezone = 'Europe/Warsaw';
```

**Comment by ywarnier** [comment] 2020-08-05 02:06
Assigned to @NicoDucou for review

**Comment by NicoDucou** [comment] 2020-08-05 12:25
I set my date.timezone to Europe/Warsaw and it took me a bit of time to find where the problem was, because most of the dates are correct, it is just on the main Course progress tool homepage that the date is still incorrect (/main/course_progress/index.php?cidReq=GITHUB3008&id_session=0&gidReq=0&gradebook=0&origin=&action=thematic_details) The date on this page is different that all the other date.

![image](https://user-images.githubusercontent.com/6579268/89412472-74b5f680-d727-11ea-926c-8fe2df91d97e.png)

We can see in the picture above that the time is 11:47 but on the edition page it shows 13:47 as show in the picture below
![image](https://user-images.githubusercontent.com/6579268/89412397-4c2dfc80-d727-11ea-9e17-c1edbae57b19.png)

**Comment by ywarnier** [comment] 2020-08-05 13:45
Oh, so this is *not* fixed by the previous commits?

**Comment by NicoDucou** [comment] 2020-08-05 15:11
As see with Carlos, what was fixed was the time on the course home page :
![image](https://user-images.githubusercontent.com/6579268/89430057-a090a680-d73e-11ea-93bc-68c93ed0fb13.png)

Carlos did not see this other problem, but will look at it now.

**Comment by carlangas159** [comment] 2020-08-05 15:59
check the list in advanced theme, the dates correspond, I found no difference, I did the test by changing the area to Berlin (different from my local time) as @NicoDucou did.

![1](https://user-images.githubusercontent.com/18097392/89435280-4970de80-d70a-11ea-8d29-3502508c7e3a.JPG)

 
Selecting the attendance list respects my hours.

![2](https://user-images.githubusercontent.com/18097392/89435370-63aabc80-d70a-11ea-9672-65192f47c1ea.JPG)

Select start time

![b1](https://user-images.githubusercontent.com/18097392/89435406-6c9b8e00-d70a-11ea-9354-15839ea7c3b4.JPG)

and it stays where @NicoDucou reports.

![f1](https://user-images.githubusercontent.com/18097392/89435468-8210b800-d70a-11ea-918c-ea2fd72c9398.JPG)

The initially reported error corresponds to the course home

**Comment by NicoDucou** [comment] 2020-08-11 08:48
As we see yesterday, I do not know why on your test it's working because on my local installation with date.timezone "Warsaw" and on 11.beeznest.com with no timezoen define in the vhost but directly the servers timezone is (UTC-0400) and we could see that the date on the home page of the course (initial problem of this task) and on the home page of the Thematic Advance tool the hour is not shown correctly.

**Comment by ywarnier** [comment] 2020-08-11 22:32
I have validated the PR from Carlos. It needs a bit more testing but the screenshots in the PR look like they're fixing the issue reported by Nico

**Comment by NicoDucou** [comment] 2020-08-12 06:37
I just tested it on 11.beeznest.com and on local where I could reproduce the problem and it is fixed in both case on the course homepage and in the Thematic Advance tool home page.
So I close this task.

**Closed by NicoDucou** 2020-08-12 06:37 UTC
Labels: Enhancement, Requires testing/validation
