### ISSUE TITLE
1.11.6 - Relative path for images, ../ missing

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#2586] opened 2018-07-12 19:39 UTC
Hi,
When importing a new image in a "document" (creating a course in LP), the access path is now relative (so the export would work with any platform structure), but the image is not displaying, because when you go to properties, thepath should be ../../ and the rest of the path, but the actual path is ../, meaning that an extra ../ is missing to do the job

Having a relative path without having to go to properties for each medium

Good luck for troubleshooting ;)

**Comment by ywarnier** [comment] 2018-07-19 23:16
Hi @Coursenligne 
@jmontoyaa sent a change to the files path for export today but I'm not into the details, so if you can try again with the latest version and tell us, that would help a little.
Did you test that on 11.chamilo.org too? Can you send us a link?

**Comment by jmontoyaa** [comment] 2018-07-23 12:57
I added more fixes:

https://github.com/chamilo/chamilo-lms/commit/47542dc8685a19ef51ba9337199307607dca4988

**Comment by Coursenligne** [comment] 2018-07-31 10:42
Hi guys,
I don't know how to test (get the fix, as I tried and crashed the platform...)

**Comment by Coursenligne** [comment] 2018-08-01 06:27
Not sure if it is the same issue, but, when I put a picture (png format), I can see it on preview when composing the page, but when I chek in the course itself, the pic doesn't show-up
![capture1](https://user-images.githubusercontent.com/32436850/43504632-73bf0b7e-9564-11e8-9437-e03845bb07e7.PNG)
This first pic shows OK (after manualy reworking the link onto the server)

![capture3](https://user-images.githubusercontent.com/32436850/43504654-8bbd580c-9564-11e8-9645-bfba29158a17.PNG)
Result in the course : blank image (image doesn't show-up).

I guess both are from same fix.
Please help me so I can run a test here :)

**Comment by jmontoyaa** [comment] 2018-08-01 06:32
Not the same issue. You're using chamilo inside a directory called "chamilo1116" in your URL: "127.0.0.1/chamilo1116"

You need to add "chamilo1116" in the configuration here:

app/config/configuration.php

`$_configuration['url_append'] = 'chamilo1116';`

If it doesn't work, maybe apache is not configured to read the .htaccess file ...

**Comment by Coursenligne** [comment] 2018-08-01 06:47
Hi Julio,
I followed the fix link, selected "Raw" then copied/past the fix into the according php file (made a copy of it prior to this :) )
The same result: ../.. is missing in the relative path.

For the other issue the result is the same: the image doesn't show-up in the course....

I need to find a solution here, as I'm competiting in september with India for a LMS solution here (all the Group) and I really want to push Chamilo (+ support obviously :) )

**Comment by jmontoyaa** [comment] 2018-08-01 06:52
I added more fixes in the Chamilo LP export to a SCORM package. I'm not sure if this is the same issue.
Latest changes are in 1.11.x

**Comment by Coursenligne** [comment] 2018-08-01 06:57
Hi Julio,
OK please give me the link I'll give a hand on it.
I found an overcome so I can at least show a trial ;)

I removed all the images ; uploaded them back to "document" rather than inside the LP and in authoring tool I browsed the server (to add the image).
This time the path is not relative :)

I hope the image is saved when exporting the course :)

Thanks for the precious help Julio and Yannick

**Comment by Coursenligne** [comment] 2018-08-01 14:12
OK. Hope 1.11.8 will come soon, I can however make a POC internaly...
Many thanks for this!

**Comment by NicoDucou** [comment] 2018-08-01 20:16
So we can close this task since it can not be reproduced on 11.chamilo.org
And @Coursenligne if you still have the problem when installing Chamilo 1.11.8 when it will be available then you could open a new issue at that time or try to reproduce it on 11.chamilo.org to be able to work on it.
Is it all good for you, can we close this issue ?

**Comment by Coursenligne** [comment] 2018-08-02 18:38
OK this task can be closed as there is an overcome. Don't waste time I know you already have enough to do ;)
BUT I hope 1.11.8 will do the job (I'm really looking forward to testing it).

Thanks guys

**Comment by NicoDucou** [comment] 2018-08-02 19:29
Let us know when 1.11.8 is released how it goes for you.

**Closed by NicoDucou** 2018-08-02 19:29 UTC
Labels: More info required, Requires testing/validation
